name: Node.Js 24.x build

on:
  push:
    branches: [release/**]

jobs:
  build:
    runs-on: ubuntu-latest

    # required for pushing the coverage badge to gh-pages
    permissions:
      contents: write

    concurrency:
      group: testbuilds
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Get npm version
        id: get-npm-version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Verify Coverage Badge Version in README.md
        shell: bash
        run: |
          BADGE_VERSION=$(grep -oP 'coverage-\K(\d+\.\d+\.\d+)(?=\.svg)' README.md)
          if [ "$BADGE_VERSION" != "${{ steps.get-npm-version.outputs.VERSION }}" ]; then
            echo "Error: Coverage badge version ($BADGE_VERSION) does not match package version (${{ steps.get-npm-version.outputs.VERSION }})"
            exit 1
          fi

      - name: Update Coverage Badge
        uses: markusberg/coverage-badge-action@v2.0.0
        with:
          version: ${{ steps.get-npm-version.outputs.VERSION }}
